# -*- coding: utf-8 -*-
"""
Phase 6.1/6.2: replay screening and lightweight landscape diagnostics.

Input: phase4_2_fold_predictions_<SYSTEM>.csv generated by phase4_2_uq_gated_stacking.py.
Output:
  - phase6_replay_metrics.csv
  - phase6_uq_diagnostics.csv
  - per-system ranking and UQ/error figures
"""
import argparse
import csv
import math
import os
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


DEFAULT_ROOT = Path(r"D:\lunwen\2.1sci")
DEFAULT_PRED_DIR = DEFAULT_ROOT / "phase 4" / "uq_gated_stacking_output"
DEFAULT_OUT_DIR = DEFAULT_ROOT / "phase 6" / "replay_output"


MODEL_COLUMNS = {
    "full_gate_uq": "pred_gate_uq",
    "w_o_uq_gate": "pred_gate_no_uq",
    "ensemble_mean": "pred_ensemble_mean",
    "best_single": "pred_best_single",
}


def read_prediction_csv(path):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        return []
    for row in rows:
        for key, value in list(row.items()):
            if key in {"sample_id", "system_id"}:
                continue
            try:
                row[key] = float(value)
            except (TypeError, ValueError):
                pass
    return rows


def relative_energy(y_true):
    arr = np.asarray(y_true, dtype=float)
    return arr - np.nanmin(arr)


def spearman_corr(x, y):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if len(x) < 2:
        return float("nan")
    rx = np.argsort(np.argsort(x)).astype(float)
    ry = np.argsort(np.argsort(y)).astype(float)
    sx = rx.std()
    sy = ry.std()
    if sx == 0 or sy == 0:
        return float("nan")
    return float(np.corrcoef(rx, ry)[0, 1])


def kendall_tau(x, y, max_pairs=200000):
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    n = len(x)
    if n < 2:
        return float("nan")
    total_pairs = n * (n - 1) // 2
    if total_pairs > max_pairs:
        rng = np.random.default_rng(42)
        pairs = rng.integers(0, n, size=(max_pairs, 2))
        pairs = pairs[pairs[:, 0] != pairs[:, 1]]
    else:
        pairs = np.array([(i, j) for i in range(n) for j in range(i + 1, n)], dtype=int)
    concordant = 0
    discordant = 0
    for i, j in pairs:
        prod = (x[i] - x[j]) * (y[i] - y[j])
        if prod > 0:
            concordant += 1
        elif prod < 0:
            discordant += 1
    denom = concordant + discordant
    return float((concordant - discordant) / denom) if denom else float("nan")


def screening_metrics(rows, model_name, pred_col, k_values, delta_thresholds):
    y_true = np.asarray([r["y_true"] for r in rows], dtype=float)
    y_pred = np.asarray([r[pred_col] for r in rows], dtype=float)
    rel_true = relative_energy(y_true)
    rel_pred = y_pred - np.nanmin(y_pred)
    order = np.argsort(y_pred)
    out = []

    for k in k_values:
        kk = min(k, len(rows))
        top = order[:kk]
        for delta in delta_thresholds:
            ref = np.where(rel_true <= delta)[0]
            recall = len(set(top.tolist()) & set(ref.tolist())) / max(1, len(ref))
            hit_mask = rel_true[top] <= delta
            if np.any(hit_mask):
                budget_to_hit = int(np.where(hit_mask)[0][0] + 1)
            else:
                budget_to_hit = -1
            contamination = float(np.mean(rel_true[top] > delta))
            out.append({
                "system": rows[0]["system_id"],
                "model": model_name,
                "K": kk,
                "delta_e_threshold": delta,
                "n_reference_low_energy": int(len(ref)),
                "recall_at_k": float(recall),
                "best_of_k_gap": float(np.nanmin(rel_true[top])),
                "budget_to_hit": budget_to_hit,
                "top_k_contamination": contamination,
                "spearman_pred_vs_true": spearman_corr(y_pred, y_true),
                "kendall_pred_vs_true": kendall_tau(y_pred, y_true),
                "mae": float(np.mean(np.abs(y_pred - y_true))),
                "mae_95": float(np.mean(np.sort(np.abs(y_pred - y_true))[-max(1, int(0.05 * len(rows))):])),
            })
    return out, rel_true, rel_pred, order


def uq_metrics(rows):
    if "uq_raw_variance" not in rows[0]:
        return None
    y_true = np.asarray([r["y_true"] for r in rows], dtype=float)
    pred = np.asarray([r["pred_ensemble_mean"] for r in rows], dtype=float)
    uq = np.asarray([r["uq_raw_variance"] for r in rows], dtype=float)
    ae = np.abs(pred - y_true)
    top_k = max(1, int(0.05 * len(rows)))
    high_uq = np.argsort(-uq)[:top_k]
    return {
        "system": rows[0]["system_id"],
        "spearman_uq_vs_abs_error": spearman_corr(uq, ae),
        "top5pct_high_uq_abs_error_mean": float(ae[high_uq].mean()),
        "all_abs_error_mean": float(ae.mean()),
        "top5pct_high_uq_error_enrichment": float(ae[high_uq].mean() / (ae.mean() + 1e-12)),
        "uq_mean": float(uq.mean()),
        "uq_max": float(uq.max()),
    }


def make_figures(rows, out_dir):
    system = rows[0]["system_id"]
    y_true = np.asarray([r["y_true"] for r in rows], dtype=float)
    rel_true = relative_energy(y_true)
    pred = np.asarray([r["pred_gate_uq"] for r in rows], dtype=float)
    rel_pred = pred - pred.min()
    uq = np.asarray([r.get("uq_raw_variance", math.nan) for r in rows], dtype=float)
    ae = np.abs(pred - y_true)
    rank = np.arange(len(rows))
    order = np.argsort(pred)

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].scatter(rank, rel_true[order], s=8, c=uq[order], cmap="viridis", alpha=0.75)
    axes[0].set_xlabel("Predicted rank by full Gate+UQ")
    axes[0].set_ylabel("True relative energy (eV)")
    axes[0].set_title(f"{system}: replay screening")
    sc = axes[1].scatter(uq, ae, s=8, c=rel_true, cmap="magma", alpha=0.75)
    axes[1].set_xlabel("Raw ensemble variance")
    axes[1].set_ylabel("Absolute error (eV)")
    axes[1].set_title(f"{system}: UQ vs error")
    fig.colorbar(sc, ax=axes[1], label="True relative energy (eV)")
    plt.tight_layout()
    path = out_dir / f"phase6_{system}_screening_uq.png"
    fig.savefig(path, dpi=160)
    plt.close(fig)


def write_csv(path, rows):
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pred-dir", default=str(DEFAULT_PRED_DIR))
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    parser.add_argument("--k", default="10,25,50,100")
    parser.add_argument("--delta", default="0.05,0.10,0.20")
    args = parser.parse_args()

    pred_dir = Path(args.pred_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    pred_files = sorted(pred_dir.glob("phase4_2_fold_predictions_*.csv"))
    if not pred_files:
        raise FileNotFoundError(
            f"No fold prediction CSVs found in {pred_dir}. "
            "Run phase4_2_uq_gated_stacking.py after this update first."
        )

    k_values = [int(x.strip()) for x in args.k.split(",") if x.strip()]
    delta_values = [float(x.strip()) for x in args.delta.split(",") if x.strip()]

    all_metrics = []
    all_uq = []
    for path in pred_files:
        rows = read_prediction_csv(path)
        if not rows:
            continue
        for model_name, pred_col in MODEL_COLUMNS.items():
            if pred_col not in rows[0]:
                continue
            metrics, _, _, _ = screening_metrics(rows, model_name, pred_col, k_values, delta_values)
            all_metrics.extend(metrics)
        uq = uq_metrics(rows)
        if uq is not None:
            all_uq.append(uq)
        make_figures(rows, out_dir)

    write_csv(out_dir / "phase6_replay_metrics.csv", all_metrics)
    write_csv(out_dir / "phase6_uq_diagnostics.csv", all_uq)
    print(f"Wrote {len(all_metrics)} screening metric rows to {out_dir / 'phase6_replay_metrics.csv'}")
    print(f"Wrote {len(all_uq)} UQ diagnostic rows to {out_dir / 'phase6_uq_diagnostics.csv'}")


if __name__ == "__main__":
    main()
